name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  unit_tests:
    name: Run NDC tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
        with:
          path: cosmos

      - name: Build connector
        run: |
          cd cosmos
          npm install
          npm run build

      - name: Download NDC Test Binary
        run: |
          curl -L https://github.com/hasura/ndc-spec/releases/download/v0.1.6/ndc-test-x86_64-unknown-linux-gnu -o ndc-test
          chmod +x ndc-test
          ./ndc-test --version  # Optional: Verify the binary works
          sudo mv ndc-test /usr/local/bin/


      - name: Verify the ndc-test binary is accessible
        run: |
          ndc-test -V

      - name: Run tests
        env:
          AZURE_COSMOS_KEY: ${{ secrets.AZURE_COSMOS_KEY }}
          AZURE_COSMOS_ENDPOINT: ${{ secrets.AZURE_COSMOS_ENDPOINT }}
          AZURE_COSMOS_DB_NAME: ${{ secrets.AZURE_COSMOS_DB_NAME }}
        run: |
          cd cosmos
          npm run ndc-test
