name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  unit_tests:
    name: Run Node.js unit tests
    runs-on: windows-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry 📦
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Azure Cosmos DB emulator
        run: >-
          Write-Host "Launching Cosmos DB Emulator"
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator
      - name: Setup database
        working-directory: ./script
        run: npm i && npm install --save @azure/cosmos && node app.js
      - name: Build connector
        run: npm run build
      - name: Start connector
        run: npm run start serve --configuration connector_config_emulator.json
      - name: Check out ndc-spec
        uses: actions/checkout@v3
        with:
          repository: hasura/ndc-spec
          path: ndc-spec
          token: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
      - name: Run ndc-test
        working-directory: ndc-spec
        run: cargo run --bin ndc-test -- replay --endpoint http://localhost:8080 --snapshots-dir ${{ github.workspace }}/ndc-test-snapshots
      # - name: Install test runner
      #   run: npm install --global mocha
      # - name: Run Node.js tests
      #   run: mocha